const data={
  jobsite:{name:'Jobsite Strong',kicker:'Nampa’s owner-operated general contractor',title:'Built to work. Built to last.',lead:'Custom homes, shops, additions, remodels, and the repairs that keep Idaho properties working right.'},
  timber:{name:'Idaho Timber',kicker:'Homes · Shops · Property Solutions',title:'Straight work. Solid results.',lead:'A warm, grounded direction for customers who value experience, honest communication, and work done right.'},
  iron:{name:'Iron & Orange',kicker:'Plan it · Build it · Finish it',title:'Jeremy gets it done.',lead:'One accountable local builder coordinating the plans, people, construction, and details from beginning to end.'},
  sawtooth:{name:'Sawtooth Custom',kicker:'Custom residential construction · Nampa, Idaho',title:'Built for the way Idaho lives.',lead:'A polished custom-builder direction with rugged roots, practical thinking, and personal project leadership.'},
  foreman:{name:'The Foreman',kicker:'Jeremy Heistand · Owner & General Contractor',title:'One call. One builder. No runaround.',lead:'From blueprints and city approvals to construction and punch-list details, Jeremy stays close to the work.'},
  workhorse:{name:'Workhorse',kicker:'Big builds · Small fixes · Same standard',title:'Whatever the property needs.',lead:'Homes, garages, additions, remodels, and handyman work from a certified and insured local contractor.'}
};
const key=document.body.dataset.concept, c=data[key]||data.jobsite;
document.body.innerHTML=`
<header class="site-head"><a class="all" href="../index.html">← All concepts</a><a href="../index.html"><img class="head-logo" src="../assets/wmb-logo.svg" alt="West Mountain Builders — Nampa, Idaho"></a><nav><a href="#services">Services</a><a href="#story">Jeremy</a><a class="call" href="tel:2088803797">208-880-3797</a></nav></header>
<main>
<section class="hero"><div class="hero-photo"></div><div class="hero-copy"><img class="hero-logo" src="../assets/wmb-logo.svg" alt="West Mountain Builders — Nampa, Idaho"><p class="kicker">${c.kicker}</p><h1>${c.title}</h1><p class="lead">${c.lead}</p><div class="actions"><a class="primary" href="tel:2088803797">Talk to Jeremy</a><a class="secondary" href="#services">See what we build</a></div></div><div class="concept-tag">${c.name} · Website direction</div></section>
<section class="proof"><div><b>Owner Operated</b><span>Jeremy is your direct contact</span></div><div><b>Certified & Insured</b><span>Professional local contractor</span></div><div><b>Plans to Finish</b><span>Full-project coordination</span></div><div><b>Nampa, Idaho</b><span>Serving the surrounding area</span></div></section>
<section class="services" id="services"><div class="section-intro"><p class="kicker">What we do</p><h2>Built for real life in Idaho.</h2><p>West Mountain Builders handles substantial construction projects and the practical work that keeps a property useful, comfortable, and strong.</p></div><div class="service-grid"><article><i>01</i><h3>Custom Homes</h3><p>Ground-up residential construction managed from early planning and blueprints through the final details.</p></article><article><i>02</i><h3>Shops & Garages</h3><p>Purpose-built structures for work, equipment, vehicles, storage, and the way you use your land.</p></article><article><i>03</i><h3>Additions & Remodels</h3><p>Structural additions and thoughtful renovations that make your existing home work better.</p></article><article><i>04</i><h3>Handyman & Repairs</h3><p>Dependable help for residential repairs, maintenance, and the jobs that simply need doing.</p></article></div></section>
<section class="story" id="story"><div class="story-photo"></div><div class="story-copy"><p class="kicker">The man behind the name</p><h2>Experienced enough to see the whole job. Hands-on enough to handle the details.</h2><p>Jeremy Heistand started in construction and spent five to six years as a project manager for an experienced builder. When the 2008 downturn hit and his mentor retired, Jeremy started working for himself. He built broad experience across construction, landscaping, irrigation, structural work, and property maintenance.</p><p>As the business grew, he formed West Mountain Builders. Today Jeremy personally helps guide projects from planning and blueprints through licensed professionals, city-approved plans when required, construction coordination, and the finishing touches.</p><div class="signature"><b>JEREMY HEISTAND</b><span>Owner · General Contractor · Problem Solver</span></div></div></section>
<section class="process"><p class="kicker">How Jeremy works</p><h2>No mystery. No runaround.</h2><div class="process-grid"><div><b>01</b><h3>Walk the job</h3><p>Start with the property, the problem, and what you want to accomplish.</p></div><div><b>02</b><h3>Make the plan</h3><p>Clarify scope, plans, approvals, trades, schedule, and the practical path forward.</p></div><div><b>03</b><h3>Build it right</h3><p>Coordinate the work, communicate directly, and keep the project moving.</p></div><div><b>04</b><h3>Finish strong</h3><p>Stay focused through the details, final touches, and the last item on the list.</p></div></div></section>
<section class="contact"><div><img src="../assets/wmb-logo.svg" alt="West Mountain Builders"></div><div><p class="kicker">Ready to talk?</p><h2>Tell Jeremy what you need built—or fixed.</h2><p>Certified and insured · Credit cards accepted</p><a class="primary" href="tel:2088803797">Call 208-880-3797</a><div class="details"><p><b>Office</b><br>1835 W Lake Point Ct<br>Nampa, ID 83651</p><p><b>Hours</b><br>Monday–Friday<br>8:00 AM–7:00 PM</p></div></div></section>
</main><footer><span>West Mountain Builders · Nampa, Idaho</span><a href="https://www.facebook.com/profile.php?id=61558865745033">Current work on Facebook →</a><a href="../index.html">View all six concepts ↑</a></footer>`;
